
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cronjobmanager.varu3.me
  resources:
  - cronjobmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronjobmanager.varu3.me
  resources:
  - cronjobmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - cronjobmanager.varu3.me
  resources:
  - cronjobmanagers/status
  verbs:
  - get
  - patch
  - update
